//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Hesabat
    {
        public static object Factory { get; internal set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> Hesabat_tarixi { get; set; }
        public Nullable<System.DateTime> Hesabat_bitme { get; set; }
        public Nullable<int> Musteri_Id { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Description { get; set; }
    
        public virtual tbl_Musteri tbl_Musteri { get; set; }
    }
}
