//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Rezerv
    {
        public int Id { get; set; }
        public Nullable<int> Musteri_Id { get; set; }
        public Nullable<int> Otag_Id { get; set; }
        public Nullable<int> Meydan_Id { get; set; }
        public Nullable<System.DateTime> Rezerv_Tarix { get; set; }
        public Nullable<int> Qiymet { get; set; }
    
        public virtual tbl_Meydan tbl_Meydan { get; set; }
        public virtual tbl_Musteri tbl_Musteri { get; set; }
        public virtual tbl_Otag tbl_Otag { get; set; }
    }
}
